/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NguoiChoi;

/**
 *
 * @author toan
 */
public class MainView extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form MainView
     */
    DefaultTableModel model1;
    DefaultTableModel model2;
    ArrayList<NguoiChoi> userList;
    public MainView() {
        initComponents();
        btnChallenge.addActionListener(this);
        model1 = (DefaultTableModel) tableUser.getModel();
        model2 = (DefaultTableModel)bangXepHang.getModel();
        
//        ArrayList<NguoiChoi> listUser = new ArrayList<>();
//        listUser.add(new NguoiChoi());
//        listUser.add(new NguoiChoi());
//        updateListUser(listUser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChallenge = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        bangXepHang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChallenge.setText("Thach Dau");

        jLabel1.setText("Xin chào:");

        jLabel2.setText("Thắng/Thua/Hòa:");

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên tài khoản", "Tên", "Trang Thai"
            }
        ));
        jScrollPane1.setViewportView(tableUser);

        jTabbedPane1.addTab("Người chơi onl", jScrollPane1);

        bangXepHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên tài khoản", "Tên", "Thắng", "Thua", "Hòa", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(bangXepHang);

        jTabbedPane1.addTab("Bảng xếp hạng", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userNameLabel)
                                .addGap(143, 143, 143)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scoreLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnChallenge)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(userNameLabel)
                    .addComponent(scoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnChallenge)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangXepHang;
    private javax.swing.JButton btnChallenge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JTable tableUser;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void challengeListener(ActionListener cha) {
        btnChallenge.addActionListener(cha);
    }

    public void updateListUser(ArrayList<NguoiChoi> userList,int currentID) {
        model1.setRowCount(0);
        model2.setRowCount(0);
        this.userList = userList;
        //Collections.sort(this.userList);
        Collections.sort(this.userList);
        int i = 0;
        for (NguoiChoi user : this.userList) {
            String str = "";
            if (user.getUserStatus() == 1) {
                str = "Online";
            } else if (user.getUserStatus() == 2) {
                str = "Ingame";
            } else if(user.getUserStatus() == 0){
                str = "offline";
            }
            if (user.getUserStatus() > 0 && user.getId() != currentID) {
                model1.addRow(new Object[]{
                    user.getUsername(),user.getFullName(), str
                });
            }
            model2.addRow(new Object[]{
                ++i,user.getUsername(),user.getFullName(),user.getWin(),user.getLose(),user.getDraw(),str
            });
        }
    }

    public NguoiChoi getSelectUser(){
        int row  = tableUser.getSelectedRow();
        if(row >= 0){
            String username = ((DefaultTableModel)tableUser.getModel()).getValueAt(row,0).toString();
            System.out.println(username);
            for(NguoiChoi user: this.userList){
                if(user.getUsername().equals(username))
                {
                    System.out.println(username);
                    return user;
                }
            }
        }
        return null;
    }
    
    public void Log(String msg){
        JOptionPane.showMessageDialog(this, msg);
    }
    
    public void setUserNameView(String userNameString) {
        userNameLabel.setText(userNameString);
    }

    public void setScoreView(String score) {
        scoreLabel.setText(score);
    }
}
