/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.View;

import Client.ControlListener.MainViewController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Timer;
import javax.swing.JOptionPane;
import model.Message;
import model.NguoiChoi;
import model.TranDau;
/**
 *
 * @author 07duc
 */
public class GameView extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form GameView
     */
    private int totalTime;
    private int timeStart;

    private NguoiChoi user1;
    private NguoiChoi user2;
    private TranDau tranDau;
    private int turn;
    private Timer timerTurn = new Timer("Timer");
    private Timer timerStart = new Timer("Timer");
    MainView mainView;
    MainViewController controller;

    public GameView(TranDau tranDau,MainViewController controller,MainView view) {
        initComponents();
        turn = 1;
        this.mainView = view;
        //visible = 0;
        this.controller = controller;
        this.tranDau = tranDau;
        this.user1 = this.tranDau.getListVanChoi().get(0).getNcvc1().getNguoiChoi();
        this.user2 = this.tranDau.getListVanChoi().get(0).getNcvc2().getNguoiChoi();
//        this.username1.setText(this.tranDau.getUserName1());
//        this.username2.setText(this.tranDau.getUserName2());
        this.resultLabel.setVisible(false);
        addWindowListener(new WindowAdapter() {
            
            @Override
            public void windowClosing(WindowEvent e) {
                //super.windowClosing(e); //To change body of generated methods, choose Tools | Templates.
                xacNhan();
            }

        });
    }

    @Override
    public void dispose() {
        mainView.setVisible(rootPaneCheckingEnabled);
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    public boolean xacNhan() {
        int choice = JOptionPane.showConfirmDialog(this, "thoat game", "Xac nhan", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            controller.sendCloseGame();
            return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBao = new javax.swing.JButton();
        btnBua = new javax.swing.JButton();
        btnKeo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        scoreUser1 = new javax.swing.JLabel();
        scoreUser2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        turnLabel = new javax.swing.JLabel();
        timeStartLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/p.png"))); // NOI18N

        btnBua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/r.png"))); // NOI18N

        btnKeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/s.png"))); // NOI18N

        btnExit.setText("Thoát");

        username1.setText("User 1");

        username2.setText("User 2");

        scoreUser1.setText("Điểm: ");

        scoreUser2.setText("Điểm: ");

        jLabel1.setText("Ván:");

        turnLabel.setText("2");

        timeStartLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        timeStartLabel.setForeground(new java.awt.Color(51, 51, 51));
        timeStartLabel.setText("Trận đấu sẽ bắt đầu trong 1s");

        timeLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 0, 51));
        timeLabel.setText("1");

        resultLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(51, 51, 51));
        resultLabel.setText("Bao thắng búa: lengan thắng");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/boy.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/boy.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(83, 83, 83)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(username1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(timeStartLabel)
                .addGap(57, 57, 57)
                .addComponent(username2)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBao)
                        .addGap(91, 91, 91)
                        .addComponent(btnBua)
                        .addGap(77, 77, 77)
                        .addComponent(btnKeo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoreUser1)
                                .addGap(310, 310, 310))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scoreUser2)
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(turnLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnExit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(turnLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeStartLabel)
                            .addComponent(username2)
                            .addComponent(username1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(timeLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreUser2)
                    .addComponent(scoreUser1))
                .addGap(23, 23, 23)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBua)
                    .addComponent(btnKeo)
                    .addComponent(btnBao))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GameView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBao;
    private javax.swing.JButton btnBua;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnKeo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel scoreUser1;
    private javax.swing.JLabel scoreUser2;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeStartLabel;
    private javax.swing.JLabel turnLabel;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    // End of variables declaration//GEN-END:variables

    public void setTimeLabelStatus(boolean status) {
        turnLabel.setVisible(status);
    }

    public void setTurnLabel(int turn) {
        turnLabel.setText(turn + "");
    }

    public void setTimeStartLabelStatus(boolean status) {
        timeStartLabel.setVisible(status);
    }

    public void setTimeStartLabel(int time) {
        timeStartLabel.setText("Ván đấu sẽ bắt đầu trong " + time + "s");
    }

    public void setResultLabelStatus(boolean status) {
        resultLabel.setVisible(status);
    }

    public void setTimeLabel(int time) {
        timeLabel.setText(time + "s");
    }

    public void addKeoButtonListener(ActionListener keo) {
        btnKeo.addActionListener(keo);
    }

    public void addBuaButtonListener(ActionListener bua) {
        btnBua.addActionListener(bua);
    }

    public void addBaoButtonListener(ActionListener bao) {
        btnBao.addActionListener(bao);
    }

    public void addExitButtonListener(ActionListener exit) {
        btnExit.addActionListener(exit);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        
    }

    public void setResultLabel(String rs) {
        this.resultLabel.setText(rs);
    }
}
